### PR TITLE
[Cl] Avoid poller callbacks blocking each other. Fixes #2578

### LINKED ISSUE #2578: Deadlock around idle timeout & close of stream with multiple substreams
### Operating System

Linux david-dev-al9.cern.ch 5.14.0-503.14.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Nov 19 21:25:22 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

### XRootD Version

v5.8.4

### Description

Process can hang after using XrdCl with multiple substreams.

### Steps to Reproduce the Behavior

Using the follwing python program (but targeting an actual running server):

```
#!/usr/bin/python3

from XRootD import client as xclient
from pyxrootd import client
import time

f1 = xclient.File()
f1.open("root://xroot-data-server.example//nonexisting-file")

time.sleep(3)
```

Run, e.g. with

XRD_LOGLEVEL=Dump XRD_TIMEOUTRESOLUTION=1 XRD_DATASERVERTTL=1 XRD_SUBSTREAMSPERCHANNEL=16 ./testpy-openwait.py

I find that often (but not always) the program never exits.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by smithdh**

### CODE REVIEW

File: src/XrdCl/XrdClChannel.hh [hunk 1]
```diff
@@ -158,7 +158,7 @@ namespace XrdCl
 
     private:
 
-      URL                    pUrl;
+      std::shared_ptr<URL>   pUrl;
```
Comment (amadio) [inline src/XrdCl/XrdClChannel.hh:161]: This is an ABI breaking change.

**Comment by abh3** [comment]
How is that? It obviously breaks internal linkage but I could not find any public dependence on ClChannel remaining unchanged.

File: src/XrdCl/XrdClChannel.hh (hunk 1 above)
Comment (amadio) [reply src/XrdCl/XrdClChannel.hh:161]: @abh3 is right, I ran the ABI check and indeed, this is not exposed in public APIs, so the change is fine, sorry for the noise.

**Comment by amadio** [comment]
@abh3 You are indeed right, the Channel implementation is not exposed, so the change passed the ABI checks. This can safely go into 5.9.

**Comment by smithdh** [comment]
I found this still needs some work; I'll have to keep in in draft for a while longer.

**Comment by amadio** [comment]
Nevermind, I see this is based on `devel`... Could you please rebase on master?
