### PR TITLE
[XrdPfc] Make sure direct vread requests conform to protocol limits.

### LINKED ISSUE #2308: Read requests fail for proxy+origin setup under heavy load
Dear xrootd developers,

At RAL we noticed that sometimes read requests fail with error `[ERROR] Server responded with an error: [3008] cannot allocate memory (source)`. After an investigation, it turned out that the error is not a simple lack of memory.

The error can be reproduced in the following way:
1. Start xrootd server and xrootd proxy on the same host, with the following configs:

proxy:
```
all.export *?
all.export /

# The adminpath and pidpath variables indicate where the pid and various
# IPC files should be placed
#
all.adminpath /var/spool/xrootd

xrootd.async off
xrd.buffers maxbsz 8m
# Configure proxy disk caching
#
ofs.osslib   libXrdPss.so
pss.cachelib libXrdPfc.so
pss.origin 127.0.0.1:1094

oss.localroot /xcache

xrd.port 1095

# Proxy settings
#
pfc.ram 1g
pfc.diskusage 0.89 0.90 purgecoldfiles 2d 5
pfc.blocksize 8m
pfc.prefetch 0
pfc.cschk off
```
server:
```
all.adminpath /var/spool/xrootd
all.pidpath /run/xrootd
```

2. Copy enough files of reasonable size to the server. For me 128 files of ~128MB in size work:
```
[root@5591c95906fc lhcb_job]# for i in {1..128}; do xrdcp testfile root://127.0.0.1:1094//tmp/file${i} ; done
[129.1MB/129.1MB][100%][==================================================][129.1MB/s]
[129.1MB/129.1MB][100%][==================================================][129.1MB/s]
[..]
```

3. Make sure that proxy's cache dir (/xcache in the above config) is empty and  for every copied file request random chunks of at least 8MiB in size via proxy. That should reproduce the error.
E.g. something like this:
```
#!/usr/bin/env python3
import sys
import random
from pyxrootd import client

if __name__ == '__main__':
    url = sys.argv[1]
    block_size = 8*1024*1024
    with client.File() as fd:
        res, _ = fd.open(url)
        if res['ok']:
            res, stat = fd.stat()
            size = stat['size']
            while True:
                offset = random.randint(0, size - 1 )
                status, res = fd.read(offset=offset, size=block_size)
                if not status['ok']:
                    print(status)
[root@5591c95906fc lhcb_job]# for i in {1..128}; do python3 test_read.py root://127.0.0.1:1095//tmp/file${i} & done
[1] 37579
[2] 37580
....
{'status': 1, 'code': 400, 'errno': 3008, 'message': '[ERROR] Server responded with an error: [3008] Unable to read /tmp/file108; cannot allocate memory\n', 'shellcode': 54, 'error': True, 'fatal': False, 'ok': False}
{'status': 1, 'code': 400, 'errno': 3008, 'message': '[ERROR] Server responded with an error: [3008] Unable to read /tmp/file86; cannot allocate memory\n', 'shellcode': 54, 'error': True, 'fatal': False, 'ok': False}
{'status': 1, 'code': 400, 'errno': 3008, 'message': '[ERROR] Server responded with an error: [3008] Unable to read /tmp/file39; cannot allocate memory\n', 'shellcode': 54, 'error': True, 'fatal': False, 'ok': False}
{'status': 1, 'code': 400, 'errno': 3008, 'message': '[ERROR] Server responded with an error: [3008] Unable to read /tmp/file85; cannot allocate memory\n', 'shellcode': 54, 'error': True, 'fatal': False, 'ok': False}
```

Obviously, in the example above proxy runs out of allocated memory, however it should be able to forward the incoming requests to the origin server, as in understand. Furthermore, it looks like the original error message coming from the server is different from the one client receives (this complicates debugging a lot...):
```
Thread 56 "xrootd" hit Breakpoint 1, XrdPosixFileRH::HandleResponse (this=0x7f9ec8001020, status=0x7faa9c001cf0, response=0x0)
    at /usr/src/debug/xrootd-5.7.0-2.el9.x86_64/src/XrdPosix/XrdPosixFileRH.cc:115
115                result = XrdPosixMap::Result(*status, theFile->ecMsg, false);
(gdb) p *status
$2 = {<XrdCl::Status> = {status = 1, code = 400, errNo = 3008}, pMessage = "Single readv transfer is too large"}
(gdb)
```

I believe, the following happens here:
1.Proxy eventually processes  Read and ReadV requests in [ReadOpusCoalescere](https://github.com/xrootd/xrootd/blob/master/src/XrdPfc/XrdPfcFile.cc#L701) function.
2. When there is lack of memory, requests are forwarded to the origin server as ReadV, even if the original request was Read -- see [here](https://github.com/xrootd/xrootd/blob/master/src/XrdPfc/XrdPfcFile.cc#L820), [here ](https://github.com/xrootd/xrootd/blob/master/src/XrdPfc/XrdPfcFile.cc#L851) and [here](https://github.com/xrootd/xrootd/blob/master/src/XrdPfc/XrdPfcFile.cc#L613).
3. ReadV requests have limit on maximum chunk size, which is defined [here ](https://github.com/xrootd/xrootd/blob/master/src/XrdXrootd/XrdXrootdProtocol.cc#L116), as far as i can see. The limit is lower than 8MiB. Read requests do not have this limit. Therefore, for example, client can submit a Read request for 8MiB block to the proxy, and if there is lack of memory, it will be forwarded to the origin server as ReadV request with one 8MiB chunk.
4. If ReadV chunk size is bigger than the limit, server will return `Single readv transfer is too large` error to the proxy, which becomes (annoyingly enough) `Cannot allocate memory` when forwarded to the client.

The above example was produced with xrootd 5.7.0, but i believe all versions from at least 5.5.4 (the one we are using in prod) are affected.

Would it be possible to amend proxy code, so that it takes into account ReadV limits of the origin server?

Best Regards,
Alex

### PR DESCRIPTION
**Pull request by osschar**
Fixes #2308.

### CODE REVIEW

**Comment by abh3** [comment]
Hmmm, where did codecov post come from? Sort of wierd I'd say as I never asked for it.

**Comment by amadio** [comment]
Codecov is the coverage tool I integrated recently. The comment is weird, I will see if I can turn it off. Just ignore it for now.

File: src/XrdPfc/XrdPfcFile.cc [hunk 1]
```diff
@@ -820,13 +832,26 @@ int File::ReadOpusCoalescere(IO *io, const XrdOucIOVec *readV, int readVnum,
...
-                  iovec_direct.back().size += size;
-               else
-                  iovec_direct.push_back( { block_idx * m_block_size + blk_off, size, 0, iUserBuff + off } );
                iovec_direct_total += size;
                read_req->m_direct_done = false;
 
+               // Make sure we do not issue a ReadV with chunk size above XrdProto::maxRVdsz.
+               // Number of actual ReadVs issued so as to not exceed the XrdProto::maxRvecsz limit
+               // is determined in the RequestBlocksDirect().
+               if (lbe == LB_direct && iovec_direct.back().size + size <= XrdProto::maxRVdsz) {
```
Comment (alex-rg) [inline src/XrdPfc/XrdPfcFile.cc:841]: Looks like the variable `XrdProto::maxRVdsz` is undefined? At least i was not able to find its definition.

Probably something like `XrdXrootdProtocol::maxReadv_ior` should be here (though it is protected...).

Comment (amadio) [reply src/XrdPfc/XrdPfcFile.cc:841]: This was defined in 5dff60cdd4a8b5ec62c52a9dc0de1590417ed6c6.

File: src/XrdPfc/XrdPfcFile.cc [hunk 2]
```diff
@@ -820,13 +832,26 @@ int File::ReadOpusCoalescere(IO *io, const XrdOucIOVec *readV, int readVnum,
...
+                  iovec_direct.back().size += size;
+               } else {
+                  long long  in_offset = block_idx * m_block_size + blk_off;
+                  char      *out_pos   = iUserBuff + off;
+                  while (size > XrdProto::maxRVdsz) {
+                     iovec_direct.push_back( { in_offset, XrdProto::maxRVdsz, 0, out_pos } );
```
Comment (amadio) [inline src/XrdPfc/XrdPfcFile.cc:847]: This is a good opportunity to use [`emplace_back`](https://en.cppreference.com/w/cpp/container/vector/emplace_back) to avoid creating a temporary object:
```suggestion
                     iovec_direct.emplace_back(in_offset, XrdProto::maxRVdsz, 0, out_pos);
```

File: src/XrdPfc/XrdPfcFile.cc [hunk 3]
```diff
@@ -820,13 +832,26 @@ int File::ReadOpusCoalescere(IO *io, const XrdOucIOVec *readV, int readVnum,
...
+                     in_offset += XrdProto::maxRVdsz;
+                     out_pos   += XrdProto::maxRVdsz;
+                     size      -= XrdProto::maxRVdsz;
+                  }
+                  iovec_direct.push_back( { in_offset, size, 0, out_pos } );
```
Comment (amadio) [inline src/XrdPfc/XrdPfcFile.cc:852]: Same here
```suggestion
                  iovec_direct.emplace_back(in_offset, size, 0, out_pos);
```

**Review by amadio — COMMENTED** [review]
Minor comments from me, if you could fix it would be nice. I disabled codecov comments now, it should not come back. The complaint from it is due to the fact that the lines being touched here are not covered by any tests, something we could look into in the near future (adding XCache tests).

File: src/XrdPfc/XrdPfcFile.cc (hunk 3 above)
Comment (osschar) [reply src/XrdPfc/XrdPfcFile.cc:852]: For this to work I have to add ctors to XrdOucIOVec:
```
       XrdOucIOVec() = default;
       XrdOucIOVec(long long offs, int sz, int inf, char *buff) :
         offset(offs), size(sz), info(inf), data(buff) {}
```
here: https://github.com/xrootd/xrootd/blob/master/src/XrdOuc/XrdOucIOVec.hh#L46

Do you want me to go forward with that?

**Comment by abh3** [comment]
Presumably those ctors will do nothing, right?

File: src/XrdPfc/XrdPfcFile.cc (hunk 3 above)
Comment (abh3) [reply src/XrdPfc/XrdPfcFile.cc:852]: Presumably the ctors will do nothing, right?

Comment (osschar) [reply src/XrdPfc/XrdPfcFile.cc:852]: Yes, they do nothing ... and they keep the automatic move ctor and operator=, the copy ctor and operator=.

Comment (amadio) [reply src/XrdPfc/XrdPfcFile.cc:852]: If the replacement I suggested doesn't work out of the box, then consider my suggestions optional. I wonder why the initializer list works then, need to take a look at this later.

**Comment by amadio** [comment]
I will merge this as is when I'm back at work. I can test if the addition of the constructors to use emplace_back are ABI compatible and do that change later if the answer is yes. Now we have tools in place to check it: https://xrootd.web.cern.ch/abi-tracker/timeline/xrootd. Have a nice weekend!

**Comment by osschar** [comment]
Thank you x 2, likewise! :)

File: src/XrdPfc/XrdPfcFile.cc (hunk 3 above)
Comment (osschar) [reply src/XrdPfc/XrdPfcFile.cc:852]: I've been wondering about this myself ... and concluded that it needs the argument-ed constructor, as done above. Initializer list was automatically promoted to move-constructor. Initializer lists are very eager to become types, too eager, I hear people say ;)
```
void push_back( T&& value );
// vs.
template< class... Args >
void /* reference from c++17 on */ emplace_back( Args&&... args );
```
