### PR TITLE
Bridge wait/waitrsp synch. (To fix #2602)

### LINKED ISSUE #2602: Bridge re-drive is invoked after protocol is Reset
### Operating System

Alma Linux 10

### XRootD Version

5.8.4

### Description

We've noticed approximately daily crashes recently with the following stack trace:

```
#0  0x00007fae48357540 in XrdXrootdProtocol::fsError (this=this@entry=0x7fa344065678, rc=3, 
    opC=opC@entry=5 '\005', myError=..., 
    Path=Path@entry=0x7fa19805c400 "/<filename redacted>", Cgi=<optimized out>)
    at /usr/src/debug/xrootd-5.8.4-1.2.osg24.el9.x86_64/xrootd-5.8.4/src/XrdXrootd/XrdXrootdXeq.cc:3780
#1  0x00007fae4835d9b3 in XrdXrootdProtocol::do_Open (this=0x7fa344065678)
    at /usr/src/debug/xrootd-5.8.4-1.2.osg24.el9.x86_64/xrootd-5.8.4/src/XrdXrootd/XrdXrootdXeq.cc:1523
#2  0x00007fae48353848 in XrdXrootdTransit::Redrive (this=0x7fa344065670)
    at /usr/src/debug/xrootd-5.8.4-1.2.osg24.el9.x86_64/xrootd-5.8.4/src/XrdXrootd/XrdXrootdTransit.cc:460
#3  0x00007fae481caf8a in XrdScheduler::Run (this=0x414780 <XrdGlobal::Sched>)
    at /usr/src/debug/xrootd-5.8.4-1.2.osg24.el9.x86_64/xrootd-5.8.4/src/Xrd/XrdScheduler.cc:365
```

The relevant lines of code are:

```
   if (rc >= SFS_STALL)
      {SI->stallCnt++;
=>     TRACEI(STALL, Response.ID() <<"stalling client for " <<rc <<" sec");
       rs = Response.Send(kXR_wait, rc, eMsg);
       if (myError.extData()) myError.Reset();
```

Which seemed to be a funny place for a segfault!  However, unwrapping the layers of macros (and looking at the assembler), the problem is the trace includes the value of `Link->ID`.  However, per GDB, the `Link` member is set to `nullptr`, so `Link->ID` is a null pointer dereference.

This indicates `Reset` was called on the `XrdXrootdProtocol` object before the redrive fired!

I have not yet figured out how this could happen.

### Steps to Reproduce the Behavior

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by smithdh**
Opening as draft at first. For more testing.

### CODE REVIEW

File: src/Xrd/XrdPollE.hh [hunk 1]
```diff
@@ -79,5 +79,6 @@ struct epoll_event *PollTab;
        int          PollMax;
        int          WaitFd;
 XrdSysSemaphore     WaitFdSem;
+XrdSysSemaphore     WaitFdSem2;
```
Comment (bbockelm) [inline src/Xrd/XrdPollE.hh]: One minor request for future readability --

For `WaitFdSem2` here (and `waitMtx`/`waitHelper`), can you document what data is being protected by the semaphoer/mutex and the locking invariants that should be followed?

Comment (smithdh) [reply src/Xrd/XrdPollE.hh]: Thanks. I've added comments to explain further what's happening and intended here.
