### PR TITLE
[XrdCl] Add return codes for error checking in the network Event handler

### LINKED ISSUE #1934: XrdCl client crash on connection failure
Hi. The crashes below were seen in an application, 'eoscp', inside libXrdCl (eos build of xrootd, approx XRootD version 5.5.2). Believed to be in the situation where an XRootD server (the local machine on which the eoscp was running and where it was connecting to) was immediately closing connections, due to #1928. The server has two addresses (ipv4 and ipv6).

Most frequently at this location:

```
(gdb) bt
#0  XrdCl::XRootDTransport::GetHeader (this=<optimized out>, message=..., socket=0x2c021c7330) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClXRootDTransport.cc:323
#1  0x00007f90c87f1115 in XrdCl::AsyncHSReader::Read (this=0x7f90b0000960) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncHSReader.hh:90
#2  XrdCl::AsyncSocketHandler::OnReadWhileHandshaking (this=0x21c7d00) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncSocketHandler.cc:515
#3  0x00007f90c87f226d in XrdCl::AsyncSocketHandler::Event (this=0x21c7d00, type=1 '\001') at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncSocketHandler.cc:227
#4  0x00007f90c87673d8 in (anonymous namespace)::SocketCallBack::Event (this=0x7f90b0000d70, chP=<optimized out>, cbArg=<optimized out>, evFlags=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClPollerBuiltIn.cc:83
#5  0x00007f90c99f07db in XrdSys::IOEvents::Poller::CbkXeq (this=0x21a68c0, cP=0x7f90b0000d90, events=1, eNum=<optimized out>, eTxt=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEvents.cc:721
#6  0x00007f90c99f1b03 in XrdSys::IOEvents::PollE::Dispatch (this=this@entry=0x21a68c0, cP=0x7f90b0000d90, pollEv=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEventsPollE.icc:275
#7  0x00007f90c99f1ce0 in XrdSys::IOEvents::PollE::Begin (syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>, this=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEventsPollE.icc:230
#8  XrdSys::IOEvents::PollE::Begin (this=0x21a68c0, syncsem=<optimized out>, retcode=<optimized out>, eTxt=<optimized out>) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEventsPollE.icc:196
#9  0x00007f90c99ee3bd in XrdSys::IOEvents::BootStrap::Start (parg=0x7ffe8a756290) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysIOEvents.cc:149
#10 0x00007f90c99f6e27 in XrdSysThread_Xeq (myargs=0x21a6990) at /usr/src/debug/xrootd-5.5.5/src/XrdSys/XrdSysPthread.cc:86
#11 0x00007f90c73d1ea5 in start_thread () from /lib64/libpthread.so.0
#12 0x00007f90c70fab0d in clone () from /lib64/libc.so.6
```

and (less frequently) at this location:

```
(gdb) bt
#0  0x00007f2f4aab5562 in XrdCl::XRootDTransport::ProcessServerHS (this=<optimized out>, hsData=0x7f2f2c0008c0, info=0x2ada340) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClXRootDTransport.cc:1876
#1  0x00007f2f4aabb213 in XrdCl::XRootDTransport::HandShakeMain (this=0x2ab7e00, handShakeData=0x7f2f2c0008c0, channelData=...) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClXRootDTransport.cc:476
#2  0x00007f2f4aabb693 in XrdCl::XRootDTransport::HandShake (this=0x2ab7e00, handShakeData=0x7f2f2c0008c0, channelData=...) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClXRootDTransport.cc:444
#3  0x00007f2f4ab28d33 in XrdCl::AsyncSocketHandler::OnConnectionReturn (this=0x2ada8e0) at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncSocketHandler.cc:341
#4  0x00007f2f4ab2e1d1 in XrdCl::AsyncSocketHandler::Event (this=0x2ada8e0, type=4 '\004') at /usr/src/debug/xrootd-5.5.5/src/XrdCl/XrdClAsyncSocketHandler.cc:251
```

### PR DESCRIPTION
**Pull request by smithdh**
This is a (second try) fix for issue #1934. (Closes #1934)

### CODE REVIEW

**Comment by smithdh** [comment]
Sorry, converted to draft. It seems likely this still needs some work.

**Comment by smithdh** [comment]
Reworked to add return codes on to various event handlers called by AsyncSocketHandler::Event. I abandoned the previous approach of enhancing "PollerBuiltIn" to allow for a check on whether a handler has been unregistered, since the return codes seem more direct way of checking.

Return code checks allow Event to stop processing any further actions once one of the handers indicates an error.

Moving the PR out of draft status.

**Comment by smithdh** [comment]
May also help with issue #1979. (I reproduced an apparently similar deadlock, and this patch did stop the deadlock I could trigger).

File: src/XrdCl/XrdClAsyncSocketHandler.cc [hunk 1]
```diff
@@ -220,11 +221,11 @@ namespace XrdCl
     {
       pLastActivity = time(0);
       if( unlikely( pTlsHandShakeOngoing ) )
-        OnTLSHandShake();
+        st = OnTLSHandShake();
```
Comment (amadio) [inline src/XrdCl/XrdClAsyncSocketHandler.cc:224]: In reviewing this with Andy, we asked ourselves the question why on the parts where writing is concerned below, the status from `OnTLSHandShake()` and other calls is not being checked.

File: src/XrdCl/XrdClAsyncSocketHandler.hh [hunk 2]
```diff
@@ -149,67 +149,67 @@ namespace XrdCl
       //------------------------------------------------------------------------
       // Connect returned
       //------------------------------------------------------------------------
-      virtual void OnConnectionReturn();
+      virtual XRootDStatus OnConnectionReturn();
```
Comment (amadio) [inline src/XrdCl/XrdClAsyncSocketHandler.hh:152]: Andy suggests to add `XRD_WARN_UNUSED_RESULT` to these to ensure we are not ignoring any of the status being returned in other places.

File: src/XrdCl/XrdClAsyncSocketHandler.cc (hunk 1 above)
Comment (smithdh) [reply src/XrdCl/XrdClAsyncSocketHandler.cc:224]: For the call to OnTLSHandShake() below (concerning writing) the flow doesn't do anything after the call (i.e. it returns from AsyncSocketHandler::Event(), which is what I was going to do for the error case) so I didn't add the check. But it's a good point this looks quite strange perhaps it's a trap for future modifications, e.g. if something is added it might also get executed during the error condition.

**Comment by smithdh** [comment]
Pushed changes; addressing the two review comments above (i) check return code everywhere, (ii) make compiler warn on unused return code from modified methods. Also added comment(s) in code about the significance of return-ing on error during AsyncSocketHandler::Event.

**Comment by smithdh** [comment]
Hi. I think there was the suggestion during review to change to use a smaller and simpler return type for the modified methods, i.e. bool rather than XRootDStatus. This is ok for me; I need a day or so to prepare and push the changes.

**Comment by smithdh** [comment]
I've pushed  changes:

- changed return type to bool
- refactored previous read/write parts of AsyncSocketHandler::Event() into two methods EventRead() EventWrite() in order to remove the previous large number of 'st = Func();' style assignments.
- Added reset of pTlsHandShakeOngoing, pHSWaitStarted, pHSWaitSeconds=0 in AsyncSocketHandler::Connect(). This is because I made a change of logic in AsyncSocketHandler::CheckHSWait(): e.g. previously on wait-time elapse, pHSWaitSeconds was always set to 0 even if the previous SendHSMsg() caused a failure. The reset was never strictly safe (since perhaps the object is deleted or reused), however simply returning after the failure added another way for pHSWaitSeconds to be non-zero after a re-connect (I believe there were already other ways this can happen too). As there are paths where several members that track connection state are not reset on re-connect I took the opportunity to reset those in Connect(); although I don't believe this is involved in any reported problem that I've look into.
