### PR TITLE
[XrdClHttp] Cleanup pending writes on failure

### LINKED ISSUE #2731: XrdClHttp hangs on failed PUT
### Operating System

All

### XRootD Version

-

### Description

A client can queue multiple writes, queuing all but the first `ResponseHandler`.  On failure of a chunk, the continuation of the operation is rightly ignored. However, the remaining handlers in `m_pending_writes` are never fired. Thus hanging the client as can be seen in the logs below.

```
[2026-03-05 14:37:46.151024 +0100][Debug  ][XrdClHttp         ] Opening http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms (with timeout 0)
[2026-03-05 14:37:46.151077 +0100][Debug  ][XrdClHttp         ] Started a curl worker
[2026-03-05 14:37:46.151224 +0100][Debug  ][XrdClHttp         ] Started a curl worker
[2026-03-05 14:37:46.159570 +0100][Debug  ][XrdClHttp         ] Started a curl worker
[2026-03-05 14:37:46.159684 +0100][Debug  ][XrdClHttp         ] Started a curl worker
[2026-03-05 14:37:46.159868 +0100][Debug  ][XrdClHttp         ] Added request for URL http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms to worker thread for processing
[2026-03-05 14:37:46.161321 +0100][Debug  ][XrdClHttp         ] CurlStatOp::Success
[2026-03-05 14:37:46.161434 +0100][Error  ][Utility           ] The given URL is empty
[2026-03-05 14:37:46.161471 +0100][Debug  ][XrdClHttp         ] Successful stat operation on http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms (size 8388608)
[2026-03-05 14:37:46.161518 +0100][Debug  ][File              ] [0x12c5af90@file://localhost/tmp/myfile?xrdcl.requuid=76dd683a-9c2f-4818-8d50-dc6ae1513aeb] Sending a read command for handle 0x3 to localhost
[2026-03-05 14:37:46.161643 +0100][Debug  ][File              ] [0x12c5af90@file://localhost/tmp/myfile?xrdcl.requuid=76dd683a-9c2f-4818-8d50-dc6ae1513aeb] Sending a read command for handle 0x3 to localhost
[2026-03-05 14:37:46.161693 +0100][Debug  ][File              ] [0x12c5af90@file://localhost/tmp/myfile?xrdcl.requuid=76dd683a-9c2f-4818-8d50-dc6ae1513aeb] Sending a read command for handle 0x3 to localhost
[2026-03-05 14:37:46.161733 +0100][Debug  ][File              ] [0x12c5af90@file://localhost/tmp/myfile?xrdcl.requuid=76dd683a-9c2f-4818-8d50-dc6ae1513aeb] Sending a read command for handle 0x3 to localhost
[2026-03-05 14:37:46.166824 +0100][Debug  ][XrdClHttp         ] Write http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms (8388608 bytes at offset 0 with timeout 9)
[8MB/47.68MB][ 16%][========>                                         ][8MB/s]  [2026-03-05 14:37:46.166993 +0100][Debug  ][XrdClHttp         ] Added request for URL http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms to worker thread for processing
[2026-03-05 14:37:46.167898 +0100][Debug  ][File              ] [0x12c5af90@file://localhost/tmp/myfile?xrdcl.requuid=76dd683a-9c2f-4818-8d50-dc6ae1513aeb] Sending a read command for handle 0x3 to localhost
[2026-03-05 14:37:46.172229 +0100][Debug  ][XrdClHttp         ] Write http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms (8388608 bytes at offset 8388608 with timeout 9)
[2026-03-05 14:37:46.172319 +0100][Debug  ][File              ] [0x12c5af90@file://localhost/tmp/myfile?xrdcl.requuid=76dd683a-9c2f-4818-8d50-dc6ae1513aeb] Sending a read command for handle 0x3 to localhost
[2026-03-05 14:37:46.177633 +0100][Debug  ][XrdClHttp         ] Write http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms (8388608 bytes at offset 16777216 with timeout 9)
[2026-03-05 14:37:46.182281 +0100][Debug  ][XrdClHttp         ] Continuing the curl handle from op 0x12cbb010 on thread 70422
[2026-03-05 14:37:46.183228 +0100][Debug  ][XrdClHttp         ] Write http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms (8388608 bytes at offset 25165824 with timeout 9)
[2026-03-05 14:37:46.184901 +0100][Debug  ][XrdClHttp         ] PUT operation at offset 0 failed with message: Insufficient Storage
[2026-03-05 14:37:46.184962 +0100][Debug  ][XrdClHttp         ] Ignoring continuation of operation that has already completed
[2026-03-05 14:37:46.189930 +0100][Debug  ][XrdClHttp         ] Write http://localhost:7094/out_of_space_quota.txt?xrdclhttp.timeout=9s500ms (8388608 bytes at offset 33554432 with timeout 9)
[2026-03-05 14:37:51.152372 +0100][Info   ][XrdClHttp         ] Client monitoring statistics: {"event": "xrdclhttp", "start": 1772717866.150531,"now": 1772717871.152249,"file": {"prefetch": {"count": 0,"expired": 0,"failed": 0,"reads_hit": 0,"reads_miss": 0,"bytes_used": 0}},"workers": {"oldest_op":1772717870.360452,"oldest_cycle":1772717870.360451,"http_HEAD_preheader_duration":0.000419,"http_OPTIONS_200_duration":0.000033,"http_OPTIONS_200_finished":1,"http_OPTIONS_preheader_duration":0.000773,"http_OPTIONS_started":1,"http_PROPFIND_207_duration":0.000038,"http_PROPFIND_207_bytes":573,"http_PROPFIND_207_finished":1,"http_PROPFIND_preheader_duration":0.000934,"http_PROPFIND_started":1,"http_PUT_507_duration":0.000101,"http_PUT_507_finished":1,"http_PUT_preheader_duration":0.002535,"http_PUT_started":1,"conncall_error":0,"conncall_started":0,"conncall_success":0,"conncall_timeout":0},"queues": {"produced":4,"consumed":4,"pending":0,"rejected":0} }
[2026-03-05 14:37:51.360537 +0100][Debug  ][XrdClHttp         ] Curl worker thread 70419 is running 0 operations
[2026-03-05 14:37:51.360597 +0100][Debug  ][XrdClHttp         ] Curl worker thread 70421 is running 0 operations
[2026-03-05 14:37:51.360670 +0100][Debug  ][XrdClHttp         ] Curl worker thread 70418 is running 0 operations
[2026-03-05 14:37:51.360724 +0100][Debug  ][XrdClHttp         ] Curl worker thread 70424 is running 0 operations
[2026-03-05 14:37:51.360744 +0100][Debug  ][XrdClHttp         ] Curl worker thread 70420 is running 0 operations
[2026-03-05 14:37:51.360902 +0100][Debug  ][XrdClHttp         ] Curl worker thread 70423 is running 0 operations
[2026-03-05 14:37:51.362319 +0100][Debug  ][XrdClHttp         ] Curl worker thread 70425 is running 0 operations
```

### Steps to Reproduce the Behavior

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by dynamic-entropy**
Fixes #2731 

Upon failure recieved by the first put chunk, the worker thread ignores continuing the operation. This can leave pending callbacks waiting for completion before cleanup.
We ensure that remaining write callbacks are invoked upon error with the same error code as the first failure, and release the waiters.

Add tests to reproduce pending write callbacks for failed put

### CODE REVIEW

File: tests/XrdOssTests/XrdOssTests.cc [hunk 1]
```diff
@@ -50,7 +50,8 @@ class File final : public XrdOssWrapDF {
     }
 
     ssize_t Write(const void *buffer, off_t offset, size_t size) override {
-        if (m_write_fail_with_offset && offset > 0) return -errorCode;
+
+        if (m_write_fail_with_offset && offset > 8000000) return -errorCode;
```
Comment (amadio) [inline tests/XrdOssTests/XrdOssTests.cc]: This looks quite arbitrary, what's the reasoning behind 8000000?

File: tests/XRootD/http.sh [hunk 2]
```diff
@@ -409,6 +409,32 @@ function test_http() {
   run_and_assert_http_and_error_code 200 "" \
     --header "Want-Digest: crc32c" -I "${HTTP_HOST}/$alphabetFilePath"
 
+  # Test requests with new xrdcl client
+
+  # The intention below is to test for hangs / crashes hence we do not 
+  # care about the exact error codes returned
+
+  xrdclTestFilePath="$TMPDIR/xrdcl_test"
```
Comment (amadio) [inline tests/XRootD/http.sh:421]: Can you please make sure this gets cleaned up at the end of the test? Several tests now leave stuff behind in `/tmp` which accumulate over time, which is not that great. Thank you.

File: tests/XrdOssTests/XrdOssTests.cc (hunk 1 above)
Comment (amadio) [reply tests/XrdOssTests/XrdOssTests.cc]: Nevermind, I see this is in the XrdOssTests... However, is this not affecting other tests that may have been relying on the old behavior? If not, then it's fine.

File: tests/XRootD/http.sh (hunk 2 above)
Comment (dynamic-entropy) [reply tests/XRootD/http.sh:421]: hmm, i can simply delete the tmp directory created by the http tests

Comment (dynamic-entropy) [reply tests/XRootD/http.sh:421]: but also these files are not created in `/tmp`. Usually wile debugging I prefer to have the files around. 
```sh
TMPDIR=$(mktemp -d "${PWD}/${NAME}/test-XXXXXX")
```

Now, if we really want to clean these up we can change this to `TMPDIR=$(mktemp -d "${LOCAL_DIR}/test-XXXXXX")`, so the common cleanup takes care of this in `test.sh::teardown` 
```sh
rm -rf "${LOCAL_DIR}" "${REMOTE_DIR}"
```

File: tests/XrdOssTests/XrdOssTests.cc (hunk 1 above)
Comment (dynamic-entropy) [reply tests/XrdOssTests/XrdOssTests.cc]: 8MB is indeed arbitrary. I just needed something to allow more time / thus increasing the chances that the client will be able to issue multiple read requests before the failure can occur. 

I have now reduced it to 2MB, along with a note in the HTTP tests for the future. 
It did not break any other tests because none were using it.

File: tests/XRootD/http.sh [hunk 3]
```diff
@@ -348,25 +345,33 @@ function test_http() {
         local trailer_code
         trailer_code=$(echo "$trailer_line" | cut -d: -f1 | xargs)
         assert_eq "$expected_trailer_code" "$trailer_code" "$trailer_line"
+      else
+        error "Expected X-Transfer-Status trailer not found in curl verbose output."
```
Comment (dynamic-entropy) [inline tests/XRootD/http.sh:349]: Added a couple of random fixes that I realised were missing from the test. If we ask for a `--trailer`, it has to exist in the response and is not optional. We should fail if we do not find it.

File: tests/XRootD/http.sh (hunk 2 above)
Comment (amadio) [reply tests/XRootD/http.sh:421]: Yes, if your `TMPDIR` is within the build directory, it's fine, and if inside the current binary dir, it's taken care of already.
