### PR TITLE
[XrdHttp/TPC] URL encoding/decoding handles '=' sign

### LINKED ISSUE #2491: [XrdHttp] URL encoding/decoding not symmetrical
The following unit test fails:
```cpp
  {
    char input [] = "zteos64%3AMDAF5PGJ4Wa12g%3D";
    std::string unquoted(unquote(input));
    std::string quoted(quote(unquoted.c_str()));
    EXPECT_EQ(input,quoted);
  }
```

It outputs:
```
Expected equality of these values:
  input
    Which is: "zteos64%3AMDAF5PGJ4Wa12g%3D"
  quoted
    Which is: "zteos64%3AMDAF5PGJ4Wa12g="
[  FAILED  ] XrdHttpTests.urlUnquoteQuoteTest (0 ms)

```

The decoding the string and encoding the decoded string should give the original string.
I'll try to use curl_easy_escape and curl_easy_unescape

### PR DESCRIPTION
**Pull request by ccaffy**
Fixes #2491 

Please do not merge as it is not tested fully yet. But first-sight comments are welcome!

### CODE REVIEW

**Comment by ccaffy** [comment]
Funnily enough, adding the `=` sign in the encoding function makes the authentication not working.

Provided that a server has `http.header2cgi Authorization authz` configuration, the resulting CGI created out of a `curl -H 'Authorization: Bearer token'` will result in `authz%3DBearer%20eyJhbGciOiJFUzI1NiI`. This CGI had the `=` sign replaced!

This is because we have:
```cpp
    std::string hdr2cgistrEncoded = encode_str<std::string>(hdr2cgistr.c_str());
    resourceplusopaque.append(hdr2cgistrEncoded.c_str());
```

One should only encode what is after the `=` sign!

Nice catch for the CI tests with authentication!

**Comment by ccaffy** [comment]
Actually, this full code does not work anymore when adding the `=` sign to the encoding:
```cpp
void XrdHttpReq::appendOpaque(XrdOucString &s, XrdSecEntity *secent, char *hash, time_t tnow) {

  int l = 0;
  char * p = 0;
  if (opaque)
    p = opaque->Env(l);

  if (hdr2cgistr.empty() && (l < 2) && !hash) return;

  // this works in most cases, except if the url already contains the xrdhttp tokens
  s = s + "?";
  if (!hdr2cgistr.empty()) {
    s += encode_str<std::string>(hdr2cgistr.c_str()).c_str();
  }
  if (p && (l > 1)) {
    if (!hdr2cgistr.empty()) {
      s = s + "&";
    }
    s = s + encode_str<std::string>(p + 1).c_str();
  }
[...]
```

File: src/XrdHttp/XrdHttpReq.cc [hunk 1]
```diff
@@ -585,14 +585,12 @@ bool XrdHttpReq::Redir(XrdXrootd::Bridge::Context &info, //!< the result context
     redirdest += buf;
   }
 
-  redirdest += quote(resource.c_str());
+  redirdest += encode_str<std::string>(resource.c_str()).c_str();
```
Comment (amadio) [inline src/XrdHttp/XrdHttpReq.cc:588]: This looks fishy, `encode_str<std::string>`, but with `resource.c_str()`, which is a `char*`, then `.c_str()` at the end again to get from `std::string` to `char*`. Maybe some optimization is possible here?

Comment (ccaffy) [reply src/XrdHttp/XrdHttpReq.cc:588]: It's because redirdest is a XrdOucString, it allows me not to have to free the raw pointer afterwards...

File: src/XrdHttp/XrdHttpReq.cc [hunk 2]
```diff
@@ -858,11 +805,10 @@ void XrdHttpReq::parseResource(char *res) {
   resourceplusopaque = resource;
   // Whatever comes after is opaque data to be parsed
   if (strlen(p) > 1) {
-    buf = unquote(p + 1);
+    const char * buf = decode_str(p + 1).c_str();
```
Comment (amadio) [inline src/XrdHttp/XrdHttpReq.cc:808]: There's a [warning](https://my.cdash.org/viewBuildError.php?type=1&buildid=2913086) here that needs to be fixed. It's a dangling pointer to a temporary, which could cause crashes at runtime.

File: src/XrdHttp/XrdHttpUtils.hh [hunk 3]
```diff
@@ -79,15 +83,97 @@ bool Fromhexdigest(const unsigned char *input, int length, unsigned char *out);
...
+ * !!! IT MUST BE FREED AFTER USAGE USING free(...) !!!
+ */
+inline char * decode_raw(const char * str) {
+  if(!str) {
+    return nullptr;
+  }
+  size_t strLength = strlen(str);
+  // uniquely own the temporary copy
+  std::unique_ptr<char[]> buf(new char[strLength + 1]);
+  std::memcpy(buf.get(), str, strLength + 1);
```
Comment (amadio) [inline src/XrdHttp/XrdHttpUtils.hh:106]: I wonder why you preferred not to use a `std::string` here.

File: src/XrdHttp/XrdHttpUtils.hh [hunk 4]
```diff
@@ -79,15 +83,97 @@ bool Fromhexdigest(const unsigned char *input, int length, unsigned char *out);
...
+  return quote(str);
+}
+
+/**
+ * Encodes the URL passed in parameter (converts all letters consider illegal in URLs to their
+ * %XX versions).
+ * Calls quote()
+ * Returns a std::string containing the encoded string
+ */
+inline std::string encode_str(const char * str) {
```
Comment (amadio) [inline src/XrdHttp/XrdHttpUtils.hh:130]: I'd take a reference to a string here as input, to avoid having to deal with `nullptr`. Same for the other functions.

File: src/XrdHttp/XrdHttpUtils.hh (hunk 3 above)
Comment (ccaffy) [reply src/XrdHttp/XrdHttpUtils.hh:106]: It's because I cannot (look at the `unquote()` function, it does modify the char * passed in parameter).

File: src/XrdHttp/XrdHttpReq.cc [hunk 5]
```diff
@@ -858,11 +805,10 @@ void XrdHttpReq::parseResource(char *res) {
   resourceplusopaque = resource;
   // Whatever comes after is opaque data to be parsed
   if (strlen(p) > 1) {
-    buf = unquote(p + 1);
-    opaque = new XrdOucEnv(buf);
+    std::string decoded = decode_str(p + 1);
+    opaque = new XrdOucEnv(decoded.c_str());
     resourceplusopaque.append('?');
     resourceplusopaque.append(p + 1);
```
Comment (amadio) [inline src/XrdHttp/XrdHttpReq.cc:811]: Is this correct? Shouldn't `opaque` be used to append?

Comment (ccaffy) [reply src/XrdHttp/XrdHttpReq.cc:811]: Nice catch!

Comment (ccaffy) [reply src/XrdHttp/XrdHttpReq.cc:811]: NOPE :D

Comment (ccaffy) [reply src/XrdHttp/XrdHttpReq.cc:811]: The resourceplusopaque string should contain the encoded string (I checked out master and did the following breakpoint):
```
(gdb) n
862	    opaque = new XrdOucEnv(buf);
(gdb) p buf
$4 = 0x7fffe8012e10 "test=test["
(gdb) n
863	    resourceplusopaque.append('?');
(gdb) n
250507 10:56:04 2371660 daemon.2451780:28@ccaffy-eosdev-al9 Xrootd_Protocol: f702 request timeout; read 0 of 24 bytes
250507 10:56:04 2371660 Xrd_Poll: Poller 0 enabled daemon.2451780:28@ccaffy-eosdev-al9
864	    resourceplusopaque.append(p + 1);
(gdb) n
865	    free(buf);
(gdb) p resourceplusopaque
$5 = {_vptr.XrdOucString = 0x41cc10 <vtable for XrdOucString+16>, str = 0x7fffe8004f20 "/tmp/fic.txt_dest?test=test%5B", len = 30, siz = 31, 
  static blksize = -1}
(gdb) 
```

File: src/XrdHttp/XrdHttpUtils.hh (hunk 4 above)
Comment (ccaffy) [reply src/XrdHttp/XrdHttpUtils.hh:130]: I'm modifying it but this means that the user should check if the char * passed is nullptr or not (one cannot construct a string with a nullptr).

Comment (ccaffy) [reply src/XrdHttp/XrdHttpUtils.hh]: It's already the case in the code so I modified it!

**Comment by ccaffy** [comment]
> Hi @ccaffy, @abh3 says we should test the encoding/decoding of `%%` vs `;`. I hope we can do that tomorrow, then we can add this to the release.

- The `%%` does not work. It basically removes what is after: `authz%3Dzteos64%%test` becomes `authz=zteos64`.
- ';' is not handled by the `quote()` code.

So either I add those cases, or we wait 5.9 in which I plan to change quote and unquote with libcurl as I initially did ;)

File: tests/XrdHttpTests/XrdHttpTests.cc [hunk 6]
```diff
@@ -574,3 +574,78 @@ TEST(XrdHttpTests, xrdHttpReadRangeHandlerMultiChunksTwoRanges) {
     ASSERT_EQ(false, static_cast<bool>(error));
   }
 }
+
+TEST(XrdHttpTests, strDecodeEncodeTest) {
+  std::string input = "zteos64%3AMDAF5PGJ4Wa12g%3D";
+  {
+    std::string decoded(decode_str(input.c_str()));
+    std::string encoded(encode_str(decoded.c_str()));
+    ASSERT_EQ(input, encoded);
```
Comment (amadio) [inline tests/XrdHttpTests/XrdHttpTests.cc:583]: How about having the long list of encoded/decoded strings, and using a simple loop over all cases in the tests?

```cpp
const std::pair<std::string, std::string> input_pairs = { ... };

for(auto [encoded, decoded] : input_pairs) {
    ASSERT_EQ(decode_str(encoded), decoded);
    ASSERT_EQ(encoded, encode_str(decoded));
    ASSERT_EQ(encode_str(decode_str(encoded)), encoded);
    ASSERT_EQ(decode_str(encode_str(decoded)), decoded);
}
```

Comment (ccaffy) [reply tests/XrdHttpTests/XrdHttpTests.cc:583]: Yes I did it but did not push yet ;)
